Remove erroneous % signs
Unnecessary % sneaked in quite a while ago, but surprisingly they
caused no issue until Fedora 31, when this started happening:

[zaitcev@suzdal ~]$ rpmbuild -bp rpms/SPECS/openstack-swift.spec
error: Cannot use %python if %__python wasn't redefined to something
 other than /usr/bin/python.
error: lua script failed: [string "<lua>"]:4: error expanding macro
error: /q/zaitcev/rpms/SPECS/openstack-swift.spec: line 11: Macro
 %pyver_sitelib failed to expand

Of course we don't support RDO on Fedora 31, but an error is
an error either way and we better fix this.

Change-Id: I091af78fb53c861f6648ffd3dc3e0d15feddd922