Update patch set 2
Patch Set 2: Code-Review-1 Workflow-1

Changing my mind, CI failure was:
Error: /Stage[main]/Swift/Package[swift]/ensure: change from absent to present failed: Execution of '/bin/yum -d 0 -e 0 -y install openstack-swift' returned 1: Error: Nothing to do

Something pulled python-swift earlier but that confuses Puppet which doesn't understand RPM provides:

Package openstack-swift-2.8.1-0.20160705194315.79be80f.el7.centos.noarch is obsoleted by python-swift-2.9.1-0.20160722041318.4bb98bc.el7.centos.noarch which is already installed
Nothing to do

Patch-set: 2
Reviewer: Gerrit User 85 <85@270e2033-b340-4cff-9539-693957ebf0e7>
Label: Code-Review=-1